development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  username: yourname
  password: passwordhere   ### password you have specified within psql
  host: localhost
  port: 5432               ### you can configure it in file postgresql.conf
  database: db/insta-development

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  username: yourname
  password: passwordhere   ### password you have specified within psql
  host: localhost
  port: 5432               ### you can configure it in file postgresql.conf
  database: db/insta-test

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  username: yourname
  password: passwordhere   ### password you have specified within psql
  host: localhost
  port: 5432               ### you can configure it in file postgresql.conf
  database: db/insta-production
  
  